### ISSUE TITLE
Add missing host type when overriding triple

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#152]
The `x86_64` part of the core agent full name appears to be missing when `triple` is set explicitly.

Check that the entire string is set correctly in all permutations of configuration.

**Comment by adamchainz** [comment]
Isn't this expected behaviour? `core_agent_triple`, if not set, is derived in https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/config.py#L196 from the current platform: https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/config.py#L14 . But if it's set explicitly, it won't be derived, so the arch and platform won't be there.

Perhaps a couple more fine grained options would help to override just `arch` and `platform` individually?

**Comment by adamchainz** [comment]
Since #259 we log a warning if `core_agent_triple` is overridden to what looks like an invalid value.
