### ISSUE TITLE
Possible to ignore transaction by name?

### ISSUE THREAD

**Issue by negativetwelve** [scoutapp/scout_apm_python#300]
We recently updated and started using #129. It is working great so far (for our graphql setup) but I was wondering if it was possible to add names to `SCOUT_IGNORE` and have it ignore the transaction by name?

We have a few auto-fetching requests similar to `/health` but are Queries in graphql. It would be great to have a way to ignore these!

**Comment by negativetwelve** [comment]
Forgot to mention, for now, we are going to try calling `ignore_transaction` by manually checking the name in our actual app code

**Comment by adamchainz** [comment]
Hi @negativetwelve 

I don't think we'd want to override the meaning of `SCOUT_IGNORE` to be both URL's and names. Rather we'd consider a new setting `SCOUT_IGNORE_NAMES`.

For now, calling `ignore_transaction` yourselves should work, and it's a bit more flexible since you can define your own boolean test (e.g. `name.startswith`).

Thanks,

Adam

**Comment by negativetwelve** [comment]
that sounds good, it's working pretty well for us. The only downside I see is that it requires a code change whenever we want to update this list. Thanks for the quick response!

**Comment by adamchainz** [comment]
You can always make your code use an environment variable, e.g.

```python
ignore_names = os.environ["MYPROJECT_SCOUT_IGNORE_NAMES"].split(",")
if name in ignore_names:
     ignore_transaction()
```

Ultimately this snippet represents the same logic we'd build if we were to add a `SCOUT_IGNORE_NAMES` setting.

After some internal discussion we've decided it doesn't make sense to add any more ignore settings right now. This is because there are basically infinite ways to decide which transactions to ignore (by name, name prefix, IP address, load balancer header, ...).

Thanks,

Adam

**Comment by negativetwelve** [comment]
that makes sense to me! we have a similar snippet that is working just great now in production. Thanks for the discussion!
