### ISSUE TITLE
Support preserving request across asyncio tasks

### ISSUE THREAD

**Issue by adamchainz** [scoutapp/scout_apm_python#469]
Currently an async view in e.g a starlette application that launches and awaits some asyncio tasks will not have them in its trace.

Our current context holder, [asgiref.local](https://github.com/django/asgiref/blob/master/asgiref/local.py), deliberately doesn't restricts context per task. This makes sense since they can be left runnign after the request completes, for example for Starlette's background tasks.

We should provide some way of preserving the tracked request into launched tasks. Need to research state of the art here.

**Comment by bitdivision** [comment]
@adamchainz Are there any plans to solve this issue? As far as I can see this makes instrumenting anything within fastAPI / Starlette non-viable since each coroutine will get a different `TrackedRequest`?

I've implemented a fix by storing the `TrackedRequest` in a context variable and overriding the `scout_apm.api` methods to pull from that context variable, though I believe this would break background tasks. Do you have any ideas on how you would like to solve this in the long-term so as to support background tasks too?

**Comment by adamchainz** [comment]
I'm no longer maintaining Scout, @tim-schilling has taken over.
