### ISSUE TITLE
Installation seems to be broken on python3.6.4

### ISSUE THREAD

**Issue by jackton1** [scoutapp/scout_apm_python#488]
<img width="1125" alt="Screen Shot 2020-02-26 at 12 31 00 PM" src="https://user-images.githubusercontent.com/17484350/75380353-e2224900-58a4-11ea-96b3-2629b94c7107.png">

**Comment by adamchainz** [comment]
Hi @jackton1 !

Thanks for the report.

I think you're compiling with quite an old macOS / X Code / clang there. It does look however like we're using the non-standard C `__thread` keyword. Let me look into this and come back to you!

Thanks,

Adam

**Comment by jackton1** [comment]
This seems to be linked to using 

`/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6` if that helps switch to `pyenv` which seems to work fine.

**Comment by adamchainz** [comment]
I've done a bit more research. It won't help to switch pyenv. The best thing to do is upgrade your macOS, or if you can't do that, at least your C compiler `clang`. It turns out `__thread` *is* standard.

I'm also going to look into a way for Scout to install itself without the C extension if it won't compile. But I can't say when that will be done.

Thanks,

Adam

**Comment by jackton1** [comment]
Already tested  using pyenv's `python 3.6.4` and didn't have any issues.

Upgrading Mac didn't seem to help it was still pointing to the same path.

```
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76

```

**Comment by adamchainz** [comment]
How did you install Python 3.6.4 previously?
