### ISSUE TITLE
Name Django Admin Views clearer

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_python#55]
Currently, Django Admin views are captured with confusingly internal names. We should capture something clearer

![_django_object_actions_utils_change_view](https://user-images.githubusercontent.com/6119/41299370-829159f6-6e20-11e8-8bc1-a6a41fba324d.png)

**Comment by adamchainz** [comment]
I've made PR #226 to do this.

The screenshot here uses a third party package [`django-object-actions`](https://github.com/crccheck/django-object-actions) that extends the admin views and replaces them. It would need custom support to figure out which admin class it's attached to, and since it doesn't seem so popular, I'm not adding support at this time. But if it's important for a customer, I can look at it.
