### ISSUE TITLE
PEP 489 multi-phase extension module initialization

### ISSUE THREAD

**Issue by adamchainz** [scoutapp/scout_apm_python#661]
The objtrace extension module should, at least on those python versions that support it, use PEP 489 style initialization

For more links and an example see my time-machine PR: https://github.com/adamchainz/time-machine/issues/136

**Comment by tim-schilling** [comment]
Thanks Adam!

**Comment by tim-schilling** [comment]
@adamchainz I'm not very knowledgeable in this area. Can you help me understand what the path forward would be for the the thread stored variables? I can see what to do with `enabled` and `installed`, but `allocs`, `callocs`, etc are a bit confusing to me since `PyModule_GetState` is for defining a block of memory for the module. However, each of those thread stored variables would need a block of memory per thread.

It's certainly possible that I'm misunderstanding something though. Any help is appreciated.

**Comment by tim-schilling** [comment]
Closed in #665

**Comment by adamchainz** [comment]
Noice one.
